apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: namespace-controller
  name: namespace-controller
spec:
  finalizers:
  - kubernetes

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-controller-sa
  namespace: namespace-controller

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-controller-role
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get","list","watch"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-controller-role-binding
subjects:
- kind: ServiceAccount
  name: namespace-controller-sa
  namespace: namespace-controller
roleRef:
  kind: ClusterRole
  name: namespace-controller-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: namespace-controller
  namespace: namespace-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: namespace-controller
  template:
    metadata:
      labels:
        app: namespace-controller
    spec:
      serviceAccountName: namespace-controller-sa
      containers:
      - name: namespace-controller
        image: quay.io/bobby-tumur/public:latest
